### ISSUE TITLE
Items in sidebar off center and off the side of the screen

### ISSUE THREAD

**Issue by crutchcorn** [ikeydoherty/budgie-next#3]
![screenshot from 2015-04-25 19-45-15](https://cloud.githubusercontent.com/assets/9100169/7335722/7827f2ca-eb85-11e4-84be-c563640ac7f7.png)
This is from the newest build of budgie-next

**Comment by mank319** [comment]
I tried investigating into the issue and have found out that it is related to utilizing a width relative to the screen's size.

I have created a "fix" by enforcing to have at the minimum a width of 300. This value has been determined empirically by testing several GTK themes and resolutions. It may not be optimal!

Generally speaking a fully dynamic solution without any constant values would be preferable. Commenting out the overridden `get_preferred_width*` functions results in the container automatically adapting to the size taken up by his children.

However I was not able to retrieve the actual width, so that it could be utilized in ` placement()`. I have tried `get_allocated_width()` and `get_size_request()` without success.

@crutchcorn do you feel like testing [the corresponding branch](https://github.com/mank319/budgie-next/tree/fix-sidebar-width) and giving feedback?

**Comment by ikeydoherty** [comment]
So GTK placement and sizing is completely on crack.  I had a rant about this in cbba225cf3ad2ba5c125cfde49f93de21a7b202f.

GTK lies to us about placement, positioning, size and relativity at every turn. If you set a size request it will fail. If you tell those GtkLabel's to linewrap and left align they'll take halign center behaviour.
The whole thing is a completely retarded mess that honestly makes me question GTK as a toolkit.

There is no real way right now to enforce a size that the widgets adjust to, so we'll have to come up with more "solutions"

**Comment by mank319** [comment]
So what do you think about my pull request as a "temporary solution", @ikeydoherty?
Following this approach it appears to be at least "wide enough" on most GTK themes.

**Comment by ikeydoherty** [comment]
Sorted

**Comment by crutchcorn** [comment]
Sorry guys. I would have tested but I am sick and my laptop with Evolve on it is elsewhere
